### ISSUE TITLE
Error while building a Go file

### ISSUE THREAD

**Issue by MultiM25** [gopherjs/gopherjs#1016]
Hi,

So I'm here because i have to build a project using GopherJs but got an error when try to build it.

The error report : "import "/proto/client": cannot import absolute path"

The proto/client is a local package.

Thanks for reading.

**Comment by flimzy** [comment]
Thanks for the report.  However, this is expected behavior, and is common to both Go and GopherJS.  Simply put, as the error states "/proto/client" is an absolute path, by virtue of beginning with a "/" character.

Further, Go, and by extension GopherJS, does not support relative (or local) paths in reliable way.  You should always use a fully qualified import path, beginning with the hostname of your host (such as `github.com`).

Since GopherJS only supports GOPATH building at this point, you should use the full import path below your $GOPATH path.  For example, if your GOPATH value is "/usr/home/multim25/go", and your project lives in "/usr/home/multim25/go/github.com/multim25/myproject/proto/client", then your import statement should look like:

```golang
import (
    "github.com/multim25/myproject/proto/client"
)
```

**Comment by MultiM25** [comment]
Thanks for your respond, i tried by adding my module name in front of my import but nothing changed.

`cannot find package "alloasite/proto/client" in any of:
        /home/flo/go/src/wwwalloasitemod/vendor/alloasite/proto/client (vendor tree)
        /usr/local/go/src/alloasite/proto/client (from $GOROOT)
        /home/flo/go/src/alloasite/proto/client (from $GOPATH)`

( alloasite is the name of my module )
