### ISSUE TITLE
Syscall runtime errors on M1 Macs (darwin/arm64)

### ISSUE THREAD

**Issue by ANPetru** [gopherjs/gopherjs#1041]
I have been having the same issue as this one: https://github.com/gopherjs/gopherjs/issues/1027, and this commit solved the build errors :https://github.com/gopherjs/gopherjs/pull/1029

But unfortunately I am now having the following runtime error: `Uncaught Error: runtime error: native function not implemented: syscall.libc_sysctl_trampoline`

**Comment by nevkontakte** [comment]
Unfortunately, this might be tricky for be to debug, since I don't have access to an M1 Mac (or any Mac for that matter).

Is your target environment nodejs or the browser? In the latter case I'd recommend a workaround of building with GOOS=linux. At this point in time linux support is much better tested and supported.

**Comment by ANPetru** [comment]
I tried building with GOOS=linux and it work's correctly, no runtime errors. I will use this workaround for now
Thank you!

**Comment by nevkontakte** [comment]
I believe since #1111 this should no longer be an issue. Feel free to reopen if I'm mistaken.
