### ISSUE TITLE
Could the goroutines support be accomplished with generators?

### ISSUE THREAD

**Issue by getify** [gopherjs/gopherjs#107]
Apologies for not knowing much about the internals of how this works, but I was just curious when reading the discussion about how goroutines look for blocking calls and process them, etc... would it be possible to support go-style CSP goroutines more directly, using generators and a channels API, similarl to how libs like these work:

* https://github.com/jlongster/js-csp
* https://github.com/ubolonton/js-csp
* https://github.com/getify/asynquence/blob/master/contrib/README.md#go-style-csp-api-emulation (disclaimer: mine)

**Comment by neelance** [comment]
I just looked into https://github.com/google/traceur-compiler and http://facebook.github.io/regenerator/ and they both seem to use closures to create scopes for local variables. This also was my first approach for implementing goroutines, but it proved to be very slow for code that may block but in practice does not block very often (or at all). This is why I switched to a different method that has a low cost when not blocking and a higher cost for switching goroutines when code blocks. This improves the overall performance a lot.
Thus, using `yield` or `await` and a JS transpiler for browser compatibility will not lead to good performance. We can revisit this approach when those JS features have reached widespread support, but this will probably still take a while. For now, I'd like to close this issue since there is no further action I can take, except one of you has a good follow-up idea.
