### ISSUE TITLE
Unable to build with a development version of Go

### ISSUE THREAD

**Issue by darkmagic13** [gopherjs/gopherjs#1123]
When trying to build a Go app with gopherjs, I get the following:
<pre>
unable to detect Go version for "/home/user/go-linux-amd64-bootstrap": unexpected `go version` output "go version devel go1.19-1f0ef6bec7 Fri May 27 17:30:15 2022 +0000 linux/amd64\n", expected 4 words
</pre>

Go's dev versions have the extra 'devel' in their version info.

**Comment by nevkontakte** [comment]
This is working as expected. Each GopherJS release is tightly coupled with a specific minor Go version (e.g. 1.17 for the latest stable GopherJS). There is work in progress for Go 1.18 in the corresponding branch, but it isn't finished yet. If you'd like to help us get there faster - let me know and I will explain how to get started. It is unlikely that GopherJS will ever support dev versions of Go, simply because it's a too fast moving target and would require way too much effort to keep up with.

If you feel particularly adventurous, you can try setting `GOPHERJS_SKIP_VERSION_CHECK` environment variable and bypass the check, but I am certain the build will simply fail for some other reason.
