### ISSUE TITLE
js struct tag - how does it work?

### ISSUE THREAD

**Issue by madelynnblue** [gopherjs/gopherjs#114]
I'm working on reactjs bindings, but can't figure out how the struct tags work. I have:

```
type Class struct {
    DisplayName string           `js:"displayName"`
    Render      func() Component `js:"render"`
}
c := Class{
    DisplayName: "Player",
    Render: func() react.Component {
        return react.DIV
    },
}
```

Printing `c` in the js console, I get:

```
Object {$val: Object, DisplayName: "Player", Render: function, $key: function, $get: function}
```

I expected it to have members `displayName` and `render` due to the struct tags. Am I missing something?

**Comment by Archs** [comment]
Is this means that the `struct literal` in gopherjs won't work?

But `struct literal` is a powerful declarative way to do some initialization. Is there some way to make it workable?

**Comment by neelance** [comment]
Hi @Archs , please include a link to an example of your issue on http://www.gopherjs.org/play/ .

**Comment by Archs** [comment]
Hi @neelance, I'm working on a [gopherjs binding of Vue.js](https://github.com/Archs/js/tree/master/vue), a MVVM js library, which is quite like Angular.js but different.

Vuejs's initialization method takes a `js object` as parameter which contains a lot of fields. In [rusco's vuejs example](https://github.com/rusco/vue), he [uses js.M](https://github.com/rusco/vue/blob/master/js/app.go#L54) to pass  the configs to the JavaScript world, which is `quite javascript like`.

So I tried using a struct literal to pass the configs like this:
```Go
type VueOption struct {
	js.Object
	El   string `js:"el"`
	Data js.M   `js:"data"`
	Methods js.M `js:"methods"`
        ...
}

// init func
func New(opts VueOption ) *Vue {
	vm := vue.New(opts)
	return &Vue{
		Object: vm,
	}
}

// then
v := vue.New(vue.VueOption{
	El: "#demo",
	Data: js.M{
		"title": "todos",
		"todos": []js.M{
			js.M{
				"done":    true,
				"content": "Learn JavaScript",
			},
			js.M{
				"done":    false,
				"content": "Learn Vue.js",
			},
		},
	},
})
```
but it won't work. I have to use the `js.M` instead like this:
```Go
// init func
func New(opts js.M) *Vue {
	vm := vue.New(opts)
	return &Vue{
		Object: vm,
	}
}
// then
v := vue.New(js.M{
	"el": "#demo",
	"data": js.M{
		"title": "todos",
		"todos": []js.M{
			js.M{
				"done":    true,
				"content": "Learn JavaScript",
			},
			js.M{
				"done":    false,
				"content": "Learn Vue.js",
			},
		},
	},
})
```
The `js.M` way works just fine but Go's type system and `go doc`'s reference utilities can't be fully utilized and hence the declarative style of doing initialization.

I think this relates to issue:#141 since the js tags in Go struct only serve as a setter/getter shortcuts, without direct access the struct fields can't be recognized by the Js world. 

Is there some way to work around this?

**Comment by jskDr** [comment]
Hi, all.
In current version, which one is more stable between coffeescript and
pythonjs.
I believe that PythonJS will be more feasible than coffeescript because it
must be
perfectly compatible with Python except highly special cases.

On Mon, Feb 2, 2015 at 9:42 AM, Archs <notifications@github.com> wrote:

> Hi @neelance <https://github.com/neelance>, I'm working on a gopherjs
> binding of Vue.js <https://github.com/Archs/js/tree/master/vue>, a MVVM
> js library, which is quite like Angular.js but different.
>
> Vuejs's initialization method takes a js object as parameter which
> contains a lot of fields. In rusco's vuejs example
> <https://github.com/rusco/vue>, he uses js.M
> <https://github.com/rusco/vue/blob/master/js/app.go#L54> to pass the
> configs to the JavaScript world, which is quite javascript like.
>
> So I tried using a struct literal to pass the configs like this:
>
> type VueOption struct {
>     js.Object
>     El   string `js:"el"`
>     Data js.M   `js:"data"`
>     Methods js.M `js:"methods"`
>         ...
> }
> // init funcfunc New(opts VueOption ) *Vue {
>     vm := vue.New(opts)
>     return &Vue{
>         Object: vm,
>     }
> }
> // thenv := vue.New(vue.VueOption{
>     El: "#demo",
>     Data: js.M{
>         "title": "todos",
>         "todos": []js.M{
>             js.M{
>                 "done":    true,
>                 "content": "Learn JavaScript",
>             },
>             js.M{
>                 "done":    false,
>                 "content": "Learn Vue.js",
>             },
>         },
>     },
> })
>
> but it won't work. I have to use the js.M instead like this:
>
> // init funcfunc New(opts js.M) *Vue {
>     vm := vue.New(opts)
>     return &Vue{
>         Object: vm,
>     }
> }// thenv := vue.New(js.M{
>     "el": "#demo",
>     "data": js.M{
>         "title": "todos",
>         "todos": []js.M{
>             js.M{
>                 "done":    true,
>                 "content": "Learn JavaScript",
>             },
>             js.M{
>                 "done":    false,
>                 "content": "Learn Vue.js",
>             },
>         },
>     },
> })
>
> The js.M way works just fine but Go's type system and go doc's reference
> utilities can't be fully utilized and hence the declarative style of doing
> initialization.
>
> I think this relates to issue:#141
> <https://github.com/gopherjs/gopherjs/issues/141> since the js tags in Go
> struct only serve as a setter/getter shortcuts, without direct access the
> struct fields can't be recognized by the Js world.
>
> Is there some way to work around this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gopherjs/gopherjs/issues/114#issuecomment-72394013>.
>



-- 
Best regards,
James Sungjin Kim, Ph.D.
Samsung Advanced Institute of Technology (SAIT)
Samsung. Electronics Co., LTD
