### ISSUE TITLE
Better error output if error is in dependency

### ISSUE THREAD

**Issue by neelance** [gopherjs/gopherjs#119]

**Comment by shurcooL** [comment]
I do wish there was more detail here though... :(

All I have to go on is the commit message:

> only show error of import if import failed

Can you easily think of a way I can reproduce this issue (if I temporarily revert the commit that fixed it) so I can see the before and after output?

**Comment by shurcooL** [comment]
I was able to figure out what this issue was about.

Given the following incorrect program that has errors and failures to import packages (because they're missing):

```Go
package main

import "foo/bar"
import "doesnt/exist"

func main() {
	bar.Do(exist.Nothing)
	f()
}
```

The output of `go build` shows only import error messages:

```
go build
main.go:4:8: cannot find package "doesnt/exist" in any of:
	/usr/local/go/src/doesnt/exist (from $GOROOT)
	/Users/Dmitri/Dropbox/Work/2013/GoLanding/src/doesnt/exist (from $GOPATH)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/doesnt/exist
main.go:3:8: cannot find package "foo/bar" in any of:
	/usr/local/go/src/foo/bar (from $GOROOT)
	/Users/Dmitri/Dropbox/Work/2013/GoLanding/src/foo/bar (from $GOPATH)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/foo/bar
```

Output of `gophers build`, before this patch, shows those import errors in addition to other errors.

```
main.go:3:8: could not import foo/bar (cannot find package "foo/bar" in any of:
	/usr/local/go/src/foo/bar (from $GOROOT)
	/Users/Dmitri/Dropbox/Work/2013/GoLanding/src/foo/bar (from $GOPATH)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/foo/bar)
main.go:4:8: could not import doesnt/exist (cannot find package "doesnt/exist" in any of:
	/usr/local/go/src/doesnt/exist (from $GOROOT)
	/Users/Dmitri/Dropbox/Work/2013/GoLanding/src/doesnt/exist (from $GOPATH)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/doesnt/exist)
main.go:7:2: undeclared name: bar
main.go:7:9: undeclared name: exist
main.go:8:2: undeclared name: f
```

The undeclared name errors don't make much sense because they may be invalid errors once the packages are found and imported correctly. So this issue/patch is about fixing that for `gopherjs build` ouput, making it report only the first import fail error. After this issue is resolved in commit https://github.com/gopherjs/gopherjs/commit/642a7f3fafe4dc7c01179a830271aadd54641fdd, the output becomes:

```
cannot find package "foo/bar" in any of:
	/usr/local/go/src/foo/bar (from $GOROOT)
	/Users/Dmitri/Dropbox/Work/2013/GoLanding/src/foo/bar (from $GOPATH)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/foo/bar
```

However, that has 2 problems. It lists only the first missing import path, rather than all (up to 10).

Another problem is that it's missing the file name and position where the error is, which was reported in #290.
