### ISSUE TITLE
closure compiler

### ISSUE THREAD

**Issue by iansmith** [gopherjs/gopherjs#134]
I was experimenting with trying to get the size of pages down by using the [ClosureCompiler](https://developers.google.com/closure/compiler) and hoping to compile my pages with gopherjs first, then use closure to compile the result plus jquery into a single, smaller js file.

It appears that either gopherjs or the combination of gophers + jquery is doing something too aggressive for closure.  Here are the report steps (it dies inside what appears to be some part the gopherjs runtime).

```html
<!DOCTYPE html>
<html lang="en">
<body>
<div id="foo">
</div>

<!-- non-compiled -->

<!--
	<script src="/fixed/jquery-2.1.1.js"></script>
    <script src="bugrep.js"></script>
-->

<!--optimized with closure -->
<script src="bugrep.js.compiled"></script>
</body>
</html>
```

And this is the simple go file:

```go
package main

import (
	"github.com/gopherjs/jquery"
)

func main() {
	jquery.NewJQuery("div#foo").SetText("hello")
}
```

Here is the closure command (using the java-based command line tool):
`java -jar $CLOSURE_JAR --compilation_level ADVANCED_OPTIMIZATIONS --js bugrep.js /path/to/js/static/fixed/jquery-2.1.1.js --js_output_file=bugrep.js.compiled`.  The problem seems to also occur if the optimization level is `SIMPLE_OPTIMIZATIONS`.

Anybody gotten this to work?
thanks
ian

**Comment by neelance** [comment]
Stale issue. Feel free to reopen.

**Comment by dinedal** [comment]
> Can you give me more information on how to change the output to be compatible with the closure compiler?

You'd need to start here: https://developers.google.com/closure/compiler/docs/limitations#restrictions-for-all-optimization-levels

The big one I can think of is that exported functions have to be referenced by string instead of normal function name:

```javascript
obj = {}
obj.foo = function() {};

// becomes
obj['foo'] = function() {};

// ... if you want .foo to be accessible outside of the scope of the compiler
```

ClojureScript does rely heavily on this compiler to:
 - Reduce file size significantly by dead code elimination
 - Increase performance since the compiler re-writes the javascript to be faster
