### ISSUE TITLE
Very minor non-determinism in generating .js output.

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/gopherjs#152]
![image](https://cloud.githubusercontent.com/assets/1924134/5693192/cf24fdea-98c7-11e4-96e1-08159aeca794.png)

When rebuilding `playground.go` a day or two later (using the same `gopherjs` revision, I'm pretty sure), I got the above minor difference in generated code. Where is the logic that determines local variable definition order? It doesn't look like `sort.Strings` is used, but despite that the sorting order is stable. Running it multiple times just now resulted in the same output.

Very minor issue, but reporting anyway (it's also possible _I_ did something wrong).

**Comment by neelance** [comment]
Thanks for reporting this. Deterministic output is definitely a goal.

Most of the order was stable because it's the order that the variables are first used. However the calls to `objectName` at https://github.com/gopherjs/gopherjs/blob/d30b2ca127879c603c5a8a6d02abb92a51b99e3b/compiler/statements.go#L792 have no deterministic order. I just opted for the easy solution to apply `sort.Strings`.
