### ISSUE TITLE
cannot find package "fmt"

### ISSUE THREAD

**Issue by huntaub** [gopherjs/gopherjs#214]
This is likely an issue with my environment, and I have no idea why. I can build go programs normally using `go`. However, for some reason, anytime I attempt to build something with `gopherjs`, I get the following error:

    cannot find package "fmt" in any of:
    	/usr/local/go/src/pkg/fmt (from $GOROOT)
    	/Users/hunter/Documents/Developer/golang/src/fmt (from $GOPATH)

Here is the print out of my `go env`:

    GOARCH="amd64"
    GOBIN=""
    GOCHAR="6"
    GOEXE=""
    GOHOSTARCH="amd64"
    GOHOSTOS="darwin"
    GOOS="darwin"
    GOPATH="/Users/hunter/Documents/Developer/golang/"
    GORACE=""
    GOROOT="/usr/local/go"
    GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
    CC="clang"
    GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
    CXX="clang++"
    CGO_ENABLED="1"

Again, I apologize if this a simple error in my setup, but everything looks fine to me. I'm running go version 1.4.

**Comment by neelance** [comment]
What I can see is that `/usr/local/go/src/pkg/fmt` is wrong, because since Go 1.4 there is no `pkg` subdirectory in `src` any more, so the correct path is `/usr/local/go/src/fmt`. This path is determined by the `go/build` package which is a core package, so it can not really be outdated and also GopherJS can't be build with earlier versions of Go, there is a check that prevents that. That's a strange situation that you have there. ;-) Is it somehow possible that you managed to compile GopherJS with the 1.4 compiler but a 1.3 GOROOT?

**Comment by huntaub** [comment]
Ah! Or perhaps I just did not update GopherJS to the most recent version. After deleting the directory and re `go get`ing, things seemed to work out. Thanks!

**Comment by neelance** [comment]
Okay. So whatever went wrong there, I'm happy that it is resolved. :-)
