### ISSUE TITLE
Cannot get the pointer value of a function with reflect.

### ISSUE THREAD

**Issue by Splizard** [gopherjs/gopherjs#255]
This always equals 1, would expect a unique value like there are for other types.
```
reflect.ValueOf(func() {
      //Do some stuff here.
}).Pointer() == 1

//This is the Pointer() implementation for reference.
func (v Value) Pointer() uintptr {
	switch k := v.kind(); k {
	case Chan, Map, Ptr, UnsafePointer:
		if v.IsNil() {
			return 0
		}
		return v.object().Unsafe()
	case Func:
		if v.IsNil() {
			return 0
		}
		return 1
	case Slice:
		if v.IsNil() {
			return 0
		}
		return v.object().Get("$array").Unsafe()
	default:
		panic(&ValueError{"reflect.Value.Pointer", k})
	}
}


```

**Comment by shurcooL** [comment]
The [compatibility table](https://github.com/gopherjs/gopherjs/blob/master/doc/packages.md) says `reflect` is fully supported, so this behavior does not line up.

**Comment by neelance** [comment]
What do you plan to do with that pointer? The Go spec says

*Slice, map, and function values are not comparable.*

This can not be circumvented by using `reflect`, because the doc for `Pointer` says

*If v's Kind is Func, the returned pointer is an underlying code pointer, but not necessarily enough to identify a single function uniquely. The only guarantee is that the result is zero if and only if v is a nil func Value.*

The "zero" condition holds, the other values are up to the implementation. That's also why all tests of the `reflect` package pass.

**Comment by shurcooL** [comment]
I stand corrected, then the current behavior is completely valid.

**Comment by Splizard** [comment]
It would be nice if there was some uniqueness in the value as there with the standard Go compiler.

**Comment by Splizard** [comment]
I would like to compare a function in some way.

**Comment by shurcooL** [comment]
Pair the function together with some comparable value, and use that.

For example,

```Go
var funcIndex = make(map[int]func())

funcIndex[0] = func() { ... }
funcIndex[1] = func() { ... }
```

**Comment by neelance** [comment]
@Splizard As explained, even with the standard Go compiler this kind of comparison is not guaranteed to work in all cases. It can break at any time. Take a look at the 3rd part of http://stackoverflow.com/a/9644797

**Comment by Splizard** [comment]
Alright, thanks I'll have a look into that.

**Comment by neelance** [comment]
@Splizard May I close this issue?

**Comment by Splizard** [comment]
yea ok :-)
