### ISSUE TITLE
Calling a method using type.method(receiver) syntax crashes the compiler

### ISSUE THREAD

**Issue by BenLubar** [gopherjs/gopherjs#256]
Minimal repro:

```go
package foo

type T int

func (t T) Foo() {}

func bar() {
	T.Foo(0)
}
```

/cc @dominikh

**Comment by shurcooL** [comment]
Thanks for reporting! Looks like it's simply not implemented:

https://github.com/gopherjs/gopherjs/blob/65c4fa73bfc6e98aeeefadff4d1a758abd85e6b0/compiler/expressions.go#L681-L682

It covers only `types.MethodVal` and `types.FieldVal` cases, but not `types.MethodExpr`. Should be a straightforward issue to fix.

I've started a solution [here](https://github.com/shurcooL/gopherjs/commit/2444c1775f46b4d792915aff37e890be7dac0732), but @neelance will do it faster because I don't quite know what's the best form for the target generated JavaScript.

**Comment by neelance** [comment]
@BenLubar Thanks for reporting! Should be fixed now.
