### ISSUE TITLE
Apparently simple program fails to behave like native

### ISSUE THREAD

**Issue by FiloSottile** [gopherjs/gopherjs#262]
Here's a small program

```go
package main

import (
	"fmt"
	"log"
	"strings"

	"github.com/cloudflare/dns"
	"github.com/gopherjs/gopherjs/js"
)

func main() {
	js.Global.Set("go", map[string]interface{}{
		"ToDS": ToDS,
	})
}

func ToDS(zone string) {
	go func() {
		zone := "filippo.io.\t3600\tIN\tDNSKEY\t257 3 13 DGpDkudNu/XQT1KmQkXFtKCfZPxHGV07qSTIcDXS33/WtT8UUG7LyxAgKznsRSFEhiQVR53E69/E57IFm8b6Zw=="

		r := strings.NewReader(zone)
		for {
			rr, err := dns.ReadRR(r, "")
			if err != nil {
				log.Println(err)
				continue
			}
			if rr == nil {
				break
			}

			dnskey, ok := rr.(*dns.DNSKEY)
			if !ok {
				log.Println("Not a DNSKEY:", rr)
				continue
			}

			if dnskey.Flags&dns.SEP == 0 {
				// ZSK
				continue
			}

			ds1 := dnskey.ToDS(dns.SHA1)
			ds2 := dnskey.ToDS(dns.SHA256)

			js.Global.Get("document").Call("write", fmt.Sprintf("%s\n%s\n", ds1, ds2))
		}
	}()
}
```

I compile it with default options and load it in a empty page, and then from the console:

```
> go.ToDS("")
< undefined
syscall.go:44 2015/07/21 01:32:52 dns: not a TTL: "DGpDkudNu/XQT1KmQkXFtKCfZPxHGV07qSTIcDXS33/WtT8UUG7LyxAgKznsRSFEhiQVR53E69/E57IFm8b6Zw==" at line: 1:124
```

The parser fails in some weird way. Different inputs fail in different ways.

Here's a equivalent program, that I run with `go run`

```go
package main

import (
	"fmt"
	"log"
	"strings"

	"github.com/cloudflare/dns"
)

func main() {
	zone := "filippo.io.\t3600\tIN\tDNSKEY\t257 3 13 DGpDkudNu/XQT1KmQkXFtKCfZPxHGV07qSTIcDXS33/WtT8UUG7LyxAgKznsRSFEhiQVR53E69/E57IFm8b6Zw=="

	r := strings.NewReader(zone)
	for {
		rr, err := dns.ReadRR(r, "")
		if err != nil {
			log.Println(err)
			continue
		}
		if rr == nil {
			break
		}

		dnskey, ok := rr.(*dns.DNSKEY)
		if !ok {
			log.Println("Not a DNSKEY:", rr)
			continue
		}

		if dnskey.Flags&dns.SEP == 0 {
			// ZSK
			continue
		}

		ds1 := dnskey.ToDS(dns.SHA1)
		ds2 := dnskey.ToDS(dns.SHA256)

		println(fmt.Sprintf("%s\n%s\n", ds1, ds2))
	}
}
```

```
$ go run src/dnskey-to-ds/test.go
filippo.io.	3600	IN	DS	42 13 1 6D68D297C0AF610513996154BDDDEDA300831957
filippo.io.	3600	IN	DS	42 13 2 2DDD9653A96320688619B6F0EBACEC1A2F4DEBA8D563A6D37C64FB3197C108A7
```

First time gopherjs user, so I might be missing something, but it looks like a bug in the channel usage of `dns.ReadRR` ([source](https://github.com/cloudflare/dns/blob/71d0b8b3818117dd1b129de3a649a6e3c29e3a97/zscan.go#L122))

**Comment by shurcooL** [comment]
Hi @FiloSottile (I know you from Twitter and I'm a big fan of your work and use of Go!),

At first I was going to say this is likely because that `github.com/cloudflare/dns` package imports `syscall` and likely does some low level stuff that cannot run directly in the browser (like `os.Open` a file on local disk).

However, I don't think that's the problem. I think you're right and there may be sort of bug with GopherJS channel support.

I've traced the program both via `go` and `gopherjs`, and you can clearly see they start running identically, but soon there is an odd deviation in behavior:

![image](https://cloud.githubusercontent.com/assets/1924134/8791656/6c2ae3ee-2f12-11e5-9d76-cc86d00dc746.png)

Which causes the two executions to return different results:

![image](https://cloud.githubusercontent.com/assets/1924134/8791670/9a041344-2f12-11e5-8e95-c480037f069d.png)

The full log files are here: [`go.txt`](http://virtivia.com:27080/1t9cuwrwvglzq.txt) and [`gopherjs.txt`](http://virtivia.com:27080/1qfxurx2d80a7.txt).

This is definitely worth looking into and fixing, and the good news is that I think it's likely that GopherJs will soon be able to run this code successfully. Thanks for the bug report!

**Comment by shurcooL** [comment]
I've made a minimal reproducible test case for the issue:

```Go
package main

import "fmt"

type lex struct {
	token string
}

func main() {
	c := make(chan lex)
	go zlexer(c)
	for l := range c {
		fmt.Println(l)
	}
}

func zlexer(c chan lex) {
	var l lex
	defer close(c)
	l.token = "hello"
	c <- l
	l.token = "bye"
	c <- l
}
```

Expected outcome (and actual output for `gc` compiler) is:

```
{hello}
{bye}
```

Whereas GopherJS output is:

```
{bye}
{bye}
```

http://www.gopherjs.org/playground/#/r7wxXXnjHg

I have a guess the issue might be very trivial, when sending on a channel, the value should be copied, rather than original being used.

**Comment by neelance** [comment]
Yes, we have to explicitly copy the values in JS. Sorry for the trouble and thanks for reporting!

**Comment by FiloSottile** [comment]
Awesome! Thanks for the super-fast investigation and fix @shurcooL and @neelance

**Comment by neelance** [comment]
@shurcooL btw: Thanks for investigating and the test case. Because of that, I immediately knew what was wrong and how to fix it. Much appreciated.
