### ISSUE TITLE
Bootstrapping compiler

### ISSUE THREAD

**Issue by DanielHeath** [gopherjs/gopherjs#271]
Now that the compiler is written in go, would it be feasible to get it compiling with gopherjs?

Imagine being able to pull in the compiler as an external library for (eg) jsfiddle...

**Comment by shurcooL** [comment]
> Now that the compiler is written in go

Which compiler are you referring to, GopherJS itself, or the native Go compiler `gc`?

If the former, GopherJS can already bootstrap itself since a while ago. That is how the [GopherJS Playground](http://www.gopherjs.org/playground) works and compiles Go code locally.

If you mean `gc`, then it's definitely more feasible now that it's in written in Go in 1.5, but a relatively significant remaining obstacle is that `gc` uses/depends on local filesystem a lot. It does not have a way to read from and compile to a virtual filesystem, which would be needed to let it work in a JS environment. That said, what would you get out of being able to run `gc` in the browser, since it would produce binaries that the browser couldn't run anyway?

**Comment by DanielHeath** [comment]
Good point - it'd be an academic exercise at best.
