### ISSUE TITLE
How do you give a dog a bone? (passing along structs)

### ISSUE THREAD

**Issue by Tobiasartz** [gopherjs/gopherjs#280]
I'm exporting this package:
http://www.gopherjs.org/playground/#/KHTCKLfhaP

In JS I'm trying to do:
```javascript
    var treat = bone.New(1);
    var fifo = pet.New('Fifo', 7, treat);
```

The error I'm getting is:
Uncaught Error: cannot internalize main.Bone

Am I trying to use gopherjs in a way that is not supported?

**Comment by shurcooL** [comment]
I have never used [`js.MakeWrapper`](http://godoc.org/github.com/gopherjs/gopherjs/js#MakeWrapper) so it's hard for me to be sure...

> MakeWrapper creates a JavaScript object which has wrappers for the exported methods of i. Use explicit getter and setter methods to expose struct fields to JavaScript.

Your `NewBone` returns a `*js.Object` type (which comes from `js.MakeWrapper(&Bone{count})`), but `NewPet` excepts a parameter of type `Bone`.

I don't think that can work. You will need to provide a `Bone` variable to `NewPet` since that's the type it expects, and it's not one of the built-in types that can be internalized/externalized automatically. Even if that worked, it would probably not be an optimal use of GopherJS.

Ideally, you want to do as much as possible in the Go world and have a small API for talking to/from JavaScript world. That way, all your Go code is normal Go code, and you're not doing unnecessary internalization/externalization of types.

**Comment by Tobiasartz** [comment]
Perfect! 
I was trying to have my Go code be a struct factory, but it makes sense that I shouldn't be using it as such.
Thank you for answering :) :+1:
