### ISSUE TITLE
Compile go with gopherjs

### ISSUE THREAD

**Issue by ooxi** [gopherjs/gopherjs#283]
I have two questions I could not find an answer to in the documentation

 1. Is it possible to compile gopherjs with gotherjs?
 2. Since go is self hosted since 1.5, is it possible to compile go with gotherjs?

**Comment by shurcooL** [comment]
> \1. Is it possible to compile gopherjs with gotherjs?

Yes, this has been the case for a long time. GopherJS can compile itself and therefore run in the browser. That is how the [GopherJS Playground](http://www.gopherjs.org/playground/) operates - it's using GopherJS, compiled with GopherJS, running in your browser.

> \2. Since go is self hosted since 1.5, is it possible to compile go with gotherjs?

In theory it would be possible to some degree, but there are a few practical reasons why it's not already done.

1. GopherJS doesn't support **all** Go packages. It supports a lot of higher-level packages, but it not all low-level ones like `runtime`, `os/exec`, `unsafe` and others that require syscalls, disk IO, unsafe pointer arithmetic. It also doesn't support Cgo. See [compatibility table](https://github.com/gopherjs/gopherjs/blob/master/doc/packages.md) for a complete list.

  Go may need some of those unsupported packages in order to compile.

2. Go compiler reads directly from disk and writes to disk. If you're in the browser, you can't do that directly. JS execution environment itself is simply more limited. It's possible to do more when using Node.js with [system calls module](https://github.com/gopherjs/gopherjs/blob/master/doc/syscalls.md).

3. What would be the point, aside from academic and proof of concept? Running native Go compiler in a browser would generate an executable file that the browser couldn't run.

4. No one has done it yet for the above reasons. But if someone tried, they might succeed. It's possible. Just requires work and potentially resolving blocking issues.

**Comment by shurcooL** [comment]
@ooxi, also see related issue https://github.com/gopherjs/gopherjs/issues/271.

**Comment by ooxi** [comment]
Thank you very much for this detailed answer!
