### ISSUE TITLE
Is there any reason not to include wrappers around JS builtins in gopherjs/js?

### ISSUE THREAD

**Issue by flimzy** [gopherjs/gopherjs#294]
My apologies if this has already been discussed, but my search of the issue archives, and google, found nothing.

I know Go has its own libraries to handle everything in the [Builtin JS functions](http://www.w3schools.com/jsref/jsref_obj_global.asp) (with the exception of "eval", I suppose), but and that it's also pretty simple to call the JS functions inline:

    encoded := js.Global.Call("encodeURI", "http://foo.com/?foo=bar")

But as light weight as these wrappers would be, why not include them in the standard js package?  I'd rather call `js.EncodeURI(...)` than pull in a dependency on `net/url`, for instance, or define my own wrapper somewhere else.

Is there a reason it was decided not to include these in the standard JS library?

If not, i would be more than happy to submit a PR to add these.  Or if for some reason we don't want to pollute the `js` namespace, perhaps a secondary module would be in order (`jsbuiltin`??).

Thoughts?

**Comment by shurcooL** [comment]
Hi @flimzy,

Thanks for opening the issue and the PR (which contains excellent code)!

I think it's best to think of the `github.com/gopherjs/gopherjs/js` package as a very general interface to the JavaScript world. It's akin to the `reflect` package or `C` pseudo-package, needed only to access another world.

From that perspective, `github.com/gopherjs/gopherjs/js` is not a package standard JS library.

I think its goal is to be as simple and general as possible, and its API should be kept as simple as possible in order to be easier to use.

The wrappers your proposing are a great idea, but I don't think they belong in `github.com/gopherjs/gopherjs/js` package.

I suggest one of two things:

1. Make those wrappers into a Go library available, for example, at `github.com/flimzy/jsbuiltin`.

  Then, add a link to it on the Wiki page for [Bindings to JavaScript APIs and libraries](https://github.com/gopherjs/gopherjs/wiki/bindings).

2. We can consider moving that native JavaScript bindings libary under `gopherjs` organization, so it can have an import path like `github.com/gopherjs/jsbuiltin`, for example.

To conclude, I think that the GopherJS compiler and its `github.com/gopherjs/gopherjs/js` package should be as simple and minimal as possible. Their goal is to compile Go to JavaScript, and to allow accessing the JavaScript world from Go (and vice versa). All libraries, wrappers, etc., are great but belong in separate repos.

What do you think?

**Comment by shurcooL** [comment]
Also see https://github.com/gopherjs/gopherjs/issues/93#issuecomment-55538551 for a similar discussion for [`jsutil.Wrap`] helper, and the conclusion of where to best place it.

**Comment by neelance** [comment]
I agree with all @shurcooL said and I'm fine with creating `github.com/gopherjs/jsbuiltin`.

**Comment by rusco** [comment]
+1. To have such bindings would be useful to avoid reinventing the wheel.
In typescript such kind of bindings are encapsulated in the lib.d.ts file. For them it's slightly easier to define whats going in that lib, since the semantic gap Javascript vs. Typescript is much smaller. For gopherjs there is some overlap in the standard golang libs, which should be taken in consideration.

**Comment by flimzy** [comment]
Thanks for the feedback.  I'll update the PR to create the bindings in a new package (probably Monday).

In the meantime, if there are any comments in response to my questions on the PR itself, I would love to hear them, too.

**Comment by flimzy** [comment]
I have updated my PR to create the new functions in a new package `jsbuiltin`.  I've also added documentation, and some better error checking.  Unless there's additional feedback, I consider the PR ready to merge.  I may tackle `parseInt` and `parseFloat` at a later time, as they require more thought than I feel inclined to provide against a problem I'm not facing. :)

**Comment by shurcooL** [comment]
> Unless there's additional feedback, I consider the PR ready to merge.

I think you misunderstood Richard. He said he was ok with putting this package under the https://github.com/gopherjs organization namespace, not inside this repository.

**Comment by flimzy** [comment]
You're right, I did misunderstand that.

So should I create a separate repo (github.com/flimzy/jsbuiltin), then transfer ownership to the gopherjs project?

**Comment by shurcooL** [comment]
Yep.

**Comment by flimzy** [comment]
The new repo exists here: https://github.com/flimzy/jsbuiltin

I've 'go fmt'ed the code, and adde the missing `// +build js`.

Now that it is its own repo, it needs a README.md, a license, etc.  I'll work on those finishing touches tomorrow before I transfer ownership.

**Comment by shurcooL** [comment]
Sounds good. @neelance will need to [create a temporary admin team for you](https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization) to be able to transfer the repo to gopherjs org.

**Comment by neelance** [comment]
@flimzy I've added you to the web gophers team, you should now be able to transfer the repo. Thanks for contributing to the project!

**Comment by flimzy** [comment]
The new repo is now at its home in the gopherjs namespace: https://github.com/gopherjs/jsbuiltin

I didn't do anything with respect to CircleCI, as I'm unfamiliar with it, and expect I don't have the permissions necessary to complete the configuration anyway (and even if I do have that permission with my temporary admin access, I prefer to leave that in the capable hands of those of you with experience in this area).

If there is any additional work you feel the new repo needs, and which I can help with, please don't hesitate to let me know.

**Comment by flimzy** [comment]
The new repo is live, so I'm closing this issue now.

**Comment by shurcooL** [comment]
Congrats! You should add it to https://github.com/gopherjs/gopherjs/wiki/bindings.

**Comment by flimzy** [comment]
Done. :)
