### ISSUE TITLE
Link to website from repo description & README

### ISSUE THREAD

**Issue by slimsag** [gopherjs/gopherjs#314]
I have a habbit of landing on the repo page ([github.com/gopherjs/gopherjs](https://github.com/gopherjs/gopherjs)) instead of the organization page ([github.com/gopherjs](https://github.com/gopherjs)), and I'm sure others might too. I suggest:

1. Adding a link to the primary website (not just the playground) in the README.md.
2. The repo description `A compiler from Go to JavaScript for running Go code in a browser` could also include a link to the website; I've found this to be common practice among other projects.

**Comment by shurcooL** [comment]
Agreed those are good ideas when the project's website is a better place to find information than the repo for general users. But with the website not really being maintained or improved over time (compared to the repo, including [README](https://github.com/gopherjs/gopherjs#readme) and [Wiki](https://github.com/gopherjs/gopherjs/wiki), that are more well maintained), I'm unsure if doing this would be beneficial or not.

**Comment by neelance** [comment]
@slimsag To clarify: What do you want to promote? https://github.com/gopherjs or http://www.gopherjs.org/ ?

@shurcooL is right that http://www.gopherjs.org/ is not that well maintained. In general I am not a fan of project websites, except when they are really well made. If I end up at a project website, usually I immediately look for the GitHub link. This is because a GitHub project page gives me metrics like star count and project activity and a readme in a common format that gives me a good grasp about the project (whereas project websites are often quite fuzzy). This is just my personal opinion, but it explains why I am not putting that much love into the GopherJS website and focus on the readme instead.

**Comment by slimsag** [comment]
Fair points. If gopherjs.org isn't going to be well maintained then I do agree linking to it / promoting it is not a good idea. I was under the impression that over time it would expand a bit in detail, but if GitHub is considered the canonical source then we can close this issue I suppose.

**Comment by shurcooL** [comment]
I do the same.

The GopherJS Playground part of the website is the main part of the website I think is very useful. And the blog too, I suppose. But the home page feels like an inferior, slightly outdated version of the README.

Maybe we can improve things by avoiding having a home page which is a re-hashed version of the repo README (which needs to be maintained separately) and instead have it automatically pull in the latest README from the repo. It can be done with a `go generate` command for this package.

**Comment by shurcooL** [comment]
Similar to how http://awesome-go.com/ content comes directly from the canonical source at https://github.com/avelino/awesome-go/blob/master/README.md, instead of there being 2 different sources to maintain. Except it's done in the frontend and I'd prefer the README to be updated statically (via a `go generate` step).

**Comment by shurcooL** [comment]
Here's a quick implementation of what I meant at https://github.com/gopherjs/gopherjs.github.io/pull/35/files. It turns out that the README was actually pretty well maintained and almost identical to the canonical README. I think it's the rest of the page that is somewhat outdated, like the title and subtitle.

**Comment by neelance** [comment]
@shurcooL Thx for the `go generate` command.

I still hope that someone from the community with good design skills will improve the website a bit further. Should we ask on Slack if someone wants to do that?

I'll close this issue, since the initial question got resolved.

**Comment by shurcooL** [comment]
> Should we ask on Slack if someone wants to do that?

Sure, it's worth a shot. We could definitely use help there.
