### ISSUE TITLE
Vendoring and sourcemap package

### ISSUE THREAD

**Issue by davelondon** [gopherjs/gopherjs#427]
I'm getting this error:

```
cannot use m (type *"github.com/neelance/sourcemap".Map) as type *"github.com/gopherjs/gopherjs/vendor/github.com/neelance/sourcemap".Map in argument to "github.com/gopherjs/gopherjs/build".NewMappingCallback
```

I haven't used vendoring before so it's possible I'm missing something obvious... If I set ```GO15VENDOREXPERIMENT``` to ```0```, everything works. Perhaps there's a way to get a ```sourcemap.Map``` without having to import the vendored package?

I'm essentially copying [this code here](https://github.com/gopherjs/gopherjs/blob/master/tool.go#L576).

**Comment by shurcooL** [comment]
Is this https://github.com/gopherjs/gopherjs/issues/415?

**Comment by davelondon** [comment]
I don't think so... I'm not vendoring gopherjs...

**Comment by shurcooL** [comment]
In that case, can you elaborate on what you're doing? How might I be able to reproduce it?

> I'm getting this error

What did you do when you got that error? What does `go version` print?

**Comment by davelondon** [comment]
Apologies. I'll make a simple test case tomorrow.

```
$ go version
go version go1.6 darwin/amd64
```

**Comment by shurcooL** [comment]
> I'll make a simple test case tomorrow.

Thanks, that should help us get the bottom of this and resolve the issue!

**Comment by davelondon** [comment]
OK an easy way to show the problem is to take the contents of [tool.go](https://raw.githubusercontent.com/gopherjs/gopherjs/master/tool.go) and put it in a separate package. With ```GO15VENDOREXPERIMENT``` set to ```0```, ```go build``` runs successfully. With ```GO15VENDOREXPERIMENT``` set to ```1```, ```go build``` fails with the error I've described.

```
$ cd $GOPATH/src/
$ mkdir foo
$ cd foo
$ curl https://raw.githubusercontent.com/gopherjs/gopherjs/master/tool.go > main.go
$ export GO15VENDOREXPERIMENT=1
$ go build
# foo
./main.go:577: cannot use m (type *"github.com/neelance/sourcemap".Map) as type *"github.com/gopherjs/gopherjs/vendor/github.com/neelance/sourcemap".Map in argument to "github.com/gopherjs/gopherjs/build".NewMappingCallback
$ export GO15VENDOREXPERIMENT=0
$ go build
$ 
```

**Comment by shurcooL** [comment]
I understand what the problem is now, thanks for explaining @davelondon.

That seems like a legitimate issue caused by how /vendor/ works. Basically, the `github.com/gopherjs/gopherjs/build` package uses a vendored version of `sourcemap` package with raw  [0] import path of `github.com/gopherjs/gopherjs/vendor/github.com/neelance/sourcemap`. Since the /vendor/ folder located at github.com/gopherjs/gopherjs/vendor, any caller of `build. NewMappingCallback` will never be able to provide it with an instance of `*"github.com/gopherjs/gopherjs/vendor/github.com/neelance/sourcemap".Map` if the caller is outside of `github.com/gopherjs/gopherjs` directory.

Currently, I can think of 2 ways to resolve this, but there may be more:

1. Do not use /vendor/ at all.

2. Move the gopherjs binary into a subdirectory, for example `github.com/gopherjs/gopherjs/cmd/gopherjs`. Move the /vendor/ folder into that directory too, so only the `gopherjs` binary uses vendoring, and all other GopherJS libraries do not.

@neelance, what do you think about this issue?

Also, @davelondon, out of curiosity, what are you working on?

**Comment by davelondon** [comment]
Hey guys, ```github.com/neelance/sourcemap``` is a pretty simple package, so if the issue is isolated to this, perhaps we could just fork it into the gopherjs project?

I'm not a vendoring expert, but I thought it was more for applications than libraries. Imagine if everything you ```go get```'ed vendored it's dependancies, and all those dependancies vendored all their dependancies.

**Comment by davelondon** [comment]
Oh, I'm working on [Ke](http://kego.io/), which at a low level is a language independent schema language for defining json data types. On top of that is a validation framework and Go type generation / custom unmarshaling package. On top of that is an extensible web front-end for editing the data. 

The basics ([schema](https://github.com/kego/ke/tree/master/system), [struct generation](https://github.com/kego/ke/tree/master/process/generate), [validation](https://github.com/kego/ke/tree/master/process/validate), [unmarshaning](https://github.com/kego/ke/tree/master/json)) are done but it's not very useful until the front-end is finished. Towards the end of last year I wrote a bunch of front-end code in gopherjs... I got a prototype I liked working, but the code was a mess. If you run the commands on the github readme, you might see a browser pop up with a tree on the left and some edit controls on the right - it's half finished so most functions won't work.

Right now I'm working in a [vecty](https://github.com/kego/ke/tree/vecty) branch, getting a Flux router set up and converting the functionality I have to vecty. I'm still getting to grips with Flux, but I'm enjoying the concept.

**Comment by shurcooL** [comment]
> I'm not a vendoring expert, but I thought it was more for applications than libraries. Imagine if everything you ```go get```'ed vendored it's dependancies, and all those dependancies vendored all their dependancies. 

I agree, that's why I mentioned option 2 that would make only the binary vendor its dependencies, not the libraries.

I'm also still not sure why vendoring is needed at all. I asked in https://github.com/gopherjs/gopherjs/commit/58f6adb4efe61919aa52b2228615c5917889c8c7#commitcomment-16671536 and the answer from @neelance was that it'd help with keeping in sync with `astrewrite` package... But I don't understand concretely what that means (i.e., how could be out of sync if vendoring isn't done?).

**Comment by davelondon** [comment]
Yes - I didn't understand that answer from @neelance either.

**Comment by neelance** [comment]
I'm currently working on https://github.com/neelance/astrewrite, which GopherJS will use. If you update GopherJS, but not astrewrite, then you'll run into compiler errors. In the worst case, it might even compile but fail to work correctly. I want to avoid that situation.

I see why the current vendoring does not work that well. We'll have to find a better solution.

>Move the gopherjs binary into a subdirectory, for example github.com/gopherjs/gopherjs/cmd/gopherjs. Move the /vendor/ folder into that directory too, so only the gopherjs command uses vendoring, and all other GopherJS packages do not.

Unfortunately this will not work, since Go's vendoring is different than Godeps. The other packages would not "see" the vendor directory any more and thus not use it.

**Comment by neelance** [comment]
I've reverted the full vendoring of all packages. Instead, I vendor only `astrewrite` into the `compiler` directory, which is fine since the `compiler` package does not leak any data structures of that package.

@davelondon This should resolve your issue, right?

**Comment by davelondon** [comment]
Yep - works great now. Thanks!

**Comment by neelance** [comment]
:)
