### ISSUE TITLE
"undeclared name: efaceOf" build error when using different GOPATHs

### ISSUE THREAD

**Issue by fabian-z** [gopherjs/gopherjs#462]
This reproduction case evolved from issue #434. Related issue #459.

Go version go1.6.2 linux/amd64
GopherJS master https://github.com/gopherjs/gopherjs/commit/ce68d341900a377d121b925cf3454b5af31fa79d

```
$ pwd
/tmp
$ mkdir go go2
$ export GOPATH=/tmp/go
$ go get github.com/gopherjs/gopherjs
$ export PATH=/tmp/go/bin:$PATH
$ cd go2
$ mkdir -p src/testpackage/
$ cat src/testpackage/main.go 
package main

func main() {

println("Hello, world!")

}

$ export GOPATH=/tmp/go2
$ go build testpackage
$ ./testpackage 
Hello, world!
$ gopherjs build testpackage
../../usr/lib/go/src/runtime/error.go:58:7: undeclared name: efaceOf
```

**Comment by shurcooL** [comment]
Thanks for putting this together, it will help resolve the issue.

**Comment by iansmith** [comment]
I had this same problem.  The gopherjs source code (for example the gopherjs implementation of the runtime package) has to be in the GOPATH.

**Comment by fabian-z** [comment]
If this is indeed the root cause of this issue (and judging from my experience documented in #434 this may very well be the case), I would suggest that the ```gopherjs``` command should also look into /vendor of the package being build for its own source code. That would at least resolve the common case of a package which vendors all of its dependencies.

**Comment by pwaller** [comment]
I just hit this error and couldn't figure out why. What fixed it for me was to ensure gopherjs was uptodate and the run `go install -v github.com/gopherjs/gopherjs`

**Comment by shurcooL** [comment]
Thanks again for the reproduce steps.

I followed them today, and the result is different. I suspect it's because of the change to embed natives into the GopherJS build system via a virtual filesystem (commit ab917e062e6a7940608ee3c9d422382784f5a7ab).

However, the `github.com/gopherjs/gopherjs/js` package isn't embedded. So the current error is:

```
$ gopherjs build testpackage
cannot find package "github.com/gopherjs/gopherjs/js" in any of:
	/usr/local/go/src/vendor/github.com/gopherjs/gopherjs/js (vendor tree)
	/usr/local/go/src/github.com/gopherjs/gopherjs/js (from $GOROOT)
	/tmp/go3/src/github.com/gopherjs/gopherjs/js (from $GOPATH)
```

I have a fix that will resolve this issue completely. It will do so by embedding the `js` and `nosync` core GopherJS packages (they're needed to build the Go standard library with GopherJS compiler) into the GopherJS build system. It will be just like the natives that are already embedded.

**Comment by shurcooL** [comment]
I've created PR #787 that'll resolve this issue.
