### ISSUE TITLE
UTC Date internalized as Local

### ISSUE THREAD

**Issue by sirudog** [gopherjs/gopherjs#466]
Hi,

Please check this playground and let me know if it is a bug or I am doing something wrong:
http://www.gopherjs.org/playground/#/JajOYjWwf4
By typing 
`testDate(new Date(Date.UTC(1978,0,24,6,20,1,12)));`
in dev consol it logs the date in your local time zone.

I think that when internalizing a JS UTC Date, the following line handles it as LOCAL date:
https://github.com/gopherjs/gopherjs/blob/master/compiler/prelude/jsmapping.go#L199
since timePkg.Unix uses Local as its time zone internally.

Thanks

**Comment by sirudog** [comment]
OK, I have checked it and it is definitely not a bug, but it is not nice to having dates implicitly be handled in Local and passed as Local date to Go. In Go, I can do this to get back to my UTC date (which was internalized and turned into Local by gopherjs):
http://www.gopherjs.org/playground/#/Kbi4Vze3BG
Just use Time.UTC() func on the param.

Is there a better way for this? Can the internalization take care somehow the location (timezone) part of the date?

**Comment by nevkontakte** [comment]
I think the fundamental problem here is that JavaScript dates are _always_ assumed to be in the local time zone. So after a Date object is constructed with `Date.UTC()` there is no way to detect that fact. Unless JavaScript provides some sort of time zone API, there's nothing GopherJS can do here.

I think in general it is a good practice to know which time zone your code is supposed to operate in (assuming it matters for your business logic) and convert the dates into it, since users may pass you a date in any time zone (including artificially constructed ones).
