### ISSUE TITLE
Go 1.7 support

### ISSUE THREAD

**Issue by benechols-wf** [gopherjs/gopherjs#475]
Go1.7 beta is out now and would be awesome to support it (I think a lot of people will be upgrading quickly due to the performance and compiling improvements)

Not a huge hurry yet, just thought I would put in the ticket early :)

I started poking around and I think that changing runtime.go will fix half the issues
```
-const GOOS = sys.TheGoos
+const GOOS = sys.GOOS
```
And the other issue I don't fully understand (when trying to do a gopherjs build):
```
$GOROOT/src/runtime/error.go:70:9: invalid operation: e._type (variable of type *struct{_string *string}) has no field or method string
```

**Comment by shurcooL** [comment]
Great! Let's use this issue to track the development status of support for Go 1.7.

It's great that you already gave it a shot and shared some immediately visible issues to be resolved.

I'll likely start looking at this in the next few weeks, after I get some other tasks out of my pipeline.

**Comment by benechols-wf** [comment]
@shurcooL just a ping as 1.7 RC1 just came out and is slated for release end of the month :)

**Comment by shurcooL** [comment]
Roger that. I will try to look this weekend. :)

**Comment by neelance** [comment]
Some good progress for 1.7 can be found on the https://github.com/gopherjs/gopherjs/tree/go1.7 branch.

**Comment by shurcooL** [comment]
Go 1.7 has been released today.

https://blog.golang.org/go1.7

**Comment by shurcooL** [comment]
I downloaded 1.7 (`go version go1.7 darwin/amd64`), installed GopherJS on [`go1.7` branch](https://github.com/gopherjs/gopherjs/commits/go1.7) and gave it a try on some of my largest GopherJS projects. They all seemingly worked without issues.

Looking at the [CI output for that branch](https://circleci.com/gh/gopherjs/gopherjs/938), it's not too surprising because most tests are passing, except for a handful. So we're quite close.

I'll make a PR off that branch.
