### ISSUE TITLE
Closing a channel after receiving from it results in "sending on closed channel"

### ISSUE THREAD

**Issue by theclapp** [gopherjs/gopherjs#478]
```go
package main

func main() {
	ch := make(chan bool)
	go func() {
		ch <- false
	}()
	go func() {
		select {
		case <-ch:
			close(ch)
		}
	}()
}
```

Result in JS Console: Uncaught Error: runtime error: send on closed channel

See http://www.gopherjs.org/playground/#/RyMy65T8Kr

Related: gopherjs/websocket#13

**Comment by shurcooL** [comment]
I can reproduce. This is definitely a bug.

It can be made a little simpler, without the `select` statement:

```Go
package main

import "time"

func main() {
	ch := make(chan bool)
	go func() {
		ch <- false
	}()
	go func() {
		<-ch
		close(ch)
	}()

	time.Sleep(time.Second)
}
```

Results in:

```
Error: runtime error: send on closed channel
```

Works fine using `gc`.

**Comment by neelance** [comment]
@theclapp Thanks for reporting this bug.

A word of caution: Closing a channel after receiving is *always* a bad idea. This is because closing is a "send" operation which means "no more messages on this channel". Only the sending goroutine should close the channel, never the receiving end. There are several posts by the Go team stressing that point.
