### ISSUE TITLE
undeclared name: efaceOf on Go 1.7

### ISSUE THREAD

**Issue by wingyplus** [gopherjs/gopherjs#498]
I try this code:

```go
// main.go
package main

func DoesNotError() error {
       	return nil
}

func main() {
       	DoesNotError()
}
```

**Expect**
It should work fine.

**Actual**
Throws an error below:

```
$ gopherjs build main.go
../../../../go/go/src/runtime/error.go:69:7: undeclared name: efaceOf
```

**Comment by shurcooL** [comment]
Go 1.7 is not yet supported by GopherJS, there is an open issue #475 and a WIP PR #495 to resolve it.

Until then, you need to either use Go 1.6 with GopherJS, or use Go 1.7 and use `go1.7` branch of GopherJS rather than `master`, but understand that it's a WIP and may have additional issues.

I'm currently using `go1.7` branch and it seems most things work well on it.

There are some other issues related to `efaceof`, see https://github.com/gopherjs/gopherjs/search?q=efaceof&type=Issues&utf8=%E2%9C%93. But I'll close this since you mentioned Go 1.7 specifically.
