### ISSUE TITLE
Increased file sizes in GopherJS 1.7-1

### ISSUE THREAD

**Issue by bep** [gopherjs/gopherjs#503]
﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿
See this commit: 
https://github.com/bep/gr/commit/4dcf98465163b2d4881cee1fc0a2897a0c6cca1c

It is mainly a rebuild of some samples for ReactJS in GopherJS 1.7-1.

```bash
435234	examples/ajax/ajax.js
60	examples/basic-click-counter/basic-click-counter.js
60	examples/basic/basic.js
65	examples/composition/composition.js
60	examples/debounce/debounce.js
-240	examples/interop/interop-ext-reverse-bundle.js
-240	examples/interop/interop.js
1111	examples/lifecycle/lifecycle.js
1472	examples/router/router.js
```

The numbers are bytes difference between the previous build on Go 1.6.3. The Ajax sample uses both `net/http` and `encoding/json` and has increased in build size by 435234 bytes.

**Comment by shurcooL** [comment]
Thanks for reporting this @bep.

I have to say that this is an expected and normal outcome, unfortunately. At a high level, it's related to https://github.com/golang/go/issues/6853.

I was aware of this when I updated the GopherJS playground from 1.6 to 1.7. It contains the compiled versions of all supported standard library packages in its [`pkg` folder](https://github.com/gopherjs/gopherjs.github.io/tree/master/playground/pkg). When I regenerated that folder with 1.7, its total size went changed in the following way:

```
1.7 - 11,565,503 bytes for 176 items
1.6 - 10,982,677 bytes for 169 items

5.31% increase
```

This was relatively expected because the standard library has grown slightly in 1.7, as can be seen by all the new exported symbols added:

https://github.com/golang/go/blob/master/api/go1.7.txt

At the same time, GopherJS did not have any generated file size improvements applied recently, so on average, the generated output is expected to change accordingly by -5% ~ +20%, depending on exact packages being used.

The reason Go's binaries have decreased in size is because there was significant active work put in during the cycle to improve dead code elimination and improve efficiency of the export format (see https://blog.golang.org/go1.7-binary-size).

I have already acted on this problem by re-opening #136 and posting https://github.com/gopherjs/gopherjs/issues/136#issuecomment-240919591. We're going to use that issue to track this problem, so I'll close this since there's nothing actionable specific to Go 1.7 that regressed (beyond the expected increase due to stdlib growth) or needs to be fixed separately.
