### ISSUE TITLE
Build gopherjs on go tip

### ISSUE THREAD

**Issue by yanzay** [gopherjs/gopherjs#512]
Is there any reason why I should not be able to compile gopherjs not on 1.7, but on fresh tip version?
It is not allowed by this line: https://github.com/gopherjs/gopherjs/blob/master/compiler/version_check.go#L1
Is there any chance to remove this restriction? Thanks.

**Comment by shurcooL** [comment]
Officially, the current version of GopherJS supports only Go 1.7.x. That's Go 1.7, 1.7.1, and any future minor patches to 1.7, but not 1.8 and tip.

That's because 1.8/tip may have breaking changes not compatible with 1.7. Usually that's not the case at the beginning of the cycle, but it quickly becomes the case as the next Go release is closer to coming out.

So, what that means is, the goal of that line is to communicate more clearly what GopherJS currently supports and what you should expect to work (and if there are problems, report issues). But nothing's stopping you from removing that line and trying to compile/use GopherJS with tip. It may work just fine, or it may fail very badly. But it's not supported, so you can't expect us to fix problems.

You can find more background motivation why this was done in #461.

Hope that helps!
