### ISSUE TITLE
doc: explain how to re-build compiler/natives

### ISSUE THREAD

**Issue by broady** [gopherjs/gopherjs#517]
The instructions are:

Setup:
```
go get github.com/shurcooL/vfsgen/cmd/vfsgendev github.com/shurcooL/httpfs/...
```

Regenerate:
```
go generate github.com/gopherjs/gopherjs/compiler/natives && \
go install github.com/gopherjs/gopherjs && \
rm -rf $(go env GOROOT)/pkg/*_js
```

**Comment by neelance** [comment]
`rm -rf $(go env GOROOT)/pkg/*_js` should not be necessary. GopherJS should detect the changed timestamps.

**Comment by shurcooL** [comment]
Agreed, we should have a document that includes information needed for development of GopherJS. Thanks for reporting this @broady.

The question is where to keep such a document.

It can either be a section in the README... Or perhaps, let's just have a link in README that points to a wiki page. We already have a page for developer guidelines at https://github.com/gopherjs/gopherjs/wiki/Developer-Guidelines, so this can be a similar page, or maybe merge those into one. Having it be a wiki rather than in README should make updating it a little less friction I hope.

**Comment by shurcooL** [comment]
I've cleaned up that page a bit, and added a section on code generation.

https://github.com/gopherjs/gopherjs/wiki/Developer-Guidelines#code-generation

@broady, how does that look to you?

As a last step to resolve this issue, I'll make a PR to add a "Development" section in the README with a link to that page.
