### ISSUE TITLE
Generating TypeScript definitions to accompany JavaScript output

### ISSUE THREAD

**Issue by paralin** [gopherjs/gopherjs#519]
It would be nice if Gopher could potentially generate `.d.ts` files to accompany the JavaScript output so we can seamlessly call Go code from TypeScript in a "type checked" way.

**Comment by myitcv** [comment]
@shurcooL I suspect this is best achieved via "internal information", i.e. at a point in the pipeline pre-output, else we are in the realm of parsing Javascript in order to derive the `.d.ts` file

**Comment by neelance** [comment]
Which method do you want to use to call the Go code from JS? The only way to get an object with methods is https://godoc.org/github.com/gopherjs/gopherjs/js#MakeWrapper, but the return values of those methods will not be wrappers, e.g. will not have methods. Could you please post a detailed scenario of which `.d.ts` files you'd like to get?

**Comment by paralin** [comment]
Hmm. Ideally I'd like to be able to export / reference Go structs from JavaScript, I.E. if I have a GoLang struct `MyStruct` it could map to a JavaScript object prototype that you can `new MyStruct()`. 

That's probably not possible right now, which is fine. Either way, it'd be interesting to create a tool capable of exporting this kind of definitions, and I'd love it if in the future Gopher could support this kind of interaction model.

I'm going to explore more with Gopher in the coming days and learn how it works internally. Apologies for my lack of understanding right now.

**Comment by paralin** [comment]
Generating typings for things exported with wrappers would definitely be useful, as well as interface types for each of the Go structs.

**Comment by paralin** [comment]
Another example. https://github.com/gopherjs/gopherjs/wiki/JavaScript-Tips-and-Gotchas

You can "wrap" JavaScript objects to use them more natively. It'd be nice to produce a TypeScript interface from the "wrapped" struct, so that I can enforce that the JavaScript objects match up with the expected Go wrapper using TypeScript interfaces.

**Comment by neelance** [comment]
@paralin I think your idea is worth looking into, but imho it does not fit into GopherJS itself. GopherJS provides the primitives for interaction between JS and Go and maybe a few small helpers like `js.MakeWrapper`. What you're suggesting could be implemented as a code generator that emits code which uses those primitives. If you'd build such a project, I would be happy to put it under the GopherJS org namespace if you're interested in that.

**Comment by mitar** [comment]
In the past I liked the idea of node.js, so that I could write same code both in the browser and for the server. But through time I discovered that JavaScript on the server is limiting and that I would prefer something like Go on the server. Also, that there is not so much shared code really between client and server, primarily just some data validation code which I would prefer to happen on the client in the same way as the server.

So I am now looking into gopherjs as a way to expose those limited parts written in Go into frontend, so utility function for validation. And to be able to expose that together with types, as a stand-alone package would mean I could maintain only one version (Go code) while having it be compiled to JavaScript + types.

One such package is my [identifier package](https://gitlab.com/tozd/identifier) which has Go and TypeScript/JavaScript implementation. It is small utility, so for now it is not hard to keep implementations in sync, but it would be great to be able to automatically generate the TypeScript version of the package.
