### ISSUE TITLE
Browser: Stub filesystem

### ISSUE THREAD

**Issue by ajackson-cpi** [gopherjs/gopherjs#591]
Is there a way to implement OS somehow so that I can simulate filesystem access in the browser?
This may be an HTTP call or something loaded in the browser.

**Comment by shurcooL** [comment]
Does it need to be related to `os` package?

You could absolutely use your own `http.FileSystem` (or equivalent interface) implementations.

**Comment by ajackson-cpi** [comment]
I'm looking to bring "standard utilities" (gocode first) entirely to the browser. The biggest challenge is to bring the files it reads over. I could hack gocode before compiling, but then I would be merging patchsets. It would be safer long-term if an implementation of http.FileSystem could replace lib "os".

**Comment by ajackson-cpi** [comment]
Can you indicate where I would start into modifying gopherJS to support pluggable OS library implementations?

**Comment by shurcooL** [comment]
It's not completely clear to me what you mean by "pluggable OS library implementations".

If you're looking to modify the `os` package implementation under GopherJS compiler, we have overrides for standard library packages in [`compiler/natives/src` directory](https://github.com/gopherjs/gopherjs/tree/7d94d732be268c4904141f8b8604eb2d6d6544a1/compiler/natives/src). Be sure to read [this comment](https://github.com/gopherjs/gopherjs/blob/7d94d732be268c4904141f8b8604eb2d6d6544a1/build/build.go#L156-L166) to understand how it works. Use `dev` build tag to pick up changes from filesystem instead of having to regenerate `github.com/gopherjs/gopherjs/compiler/natives` package each time you modify its contents.

However, keep in mind that if you want to be able to merge these changes upstream into GopherJS, you'll need to discuss the change, and it has to fit into the general requirements for GopherJS.

**Comment by flimzy** [comment]
Go 1.16's `io/fs` package, which is now supported in GopherJS 1.16, should allow something very close to this. Would this work for you?

If not, or you think this issue deserves more attention, please comment and we'll be happy to re-open.
