### ISSUE TITLE
Installing with the tip version of Go fails with "requires version 1.8"

### ISSUE THREAD

**Issue by rjammala** [gopherjs/gopherjs#654]
```
$ go get -u github.com/gopherjs/gopherjs
# github.com/gopherjs/gopherjs/compiler
gocode/src/github.com/gopherjs/gopherjs/compiler/compiler.go:20:9: undefined: ___GOPHERJS_REQUIRES_GO_VERSION_1_8___
```

**Comment by shurcooL** [comment]
That's because the `master` branch of GopherJS compiler requires Go 1.8, and tip contains a beta version of Go 1.9.

There is a `go1.9` branch, which is a work in progress to add support for Go 1.9. See PR #651 for details. By now, it should be stable and ready for testing and issue reports. Install it with:

```
cd $GOPATH/src/github.com/gopherjs/gopherjs
git checkout go1.9
git pull --ff-only
go install
```
