### ISSUE TITLE
Customizing gopherjs serve

### ISSUE THREAD

**Issue by beatscode** [gopherjs/gopherjs#665]
I'd like to repurpose the "serve" functionality for a custom web application.  
The problem I have is that the build functionality always writes to a file. Is there a way I could skip writing to a file and capture the contents instead? I see the BuildFiles function seems to kick off the export phase. Does the serve watcher run buildFiles as well?

**Comment by shurcooL** [comment]
> The problem I have is that the build functionality always writes to a file. Is there a way I could skip writing to a file and capture the contents instead?

You might want to look at using [`github.com/shurcooL/go/gopherjs_http`](https://godoc.org/github.com/shurcooL/go/gopherjs_http).

Either `gopherjs_http.NewFS` to be able to access/compile any package, or `gopherjs_http.Package` to build a single specific package.

`gopherjs_http` functionality is built on top of [`github.com/shurcooL/gopherjslib`](https://godoc.org/github.com/shurcooL/gopherjslib) API, which in turn is built on top of [`github.com/gopherjs/gopherjs/compiler`](https://godoc.org/github.com/gopherjs/gopherjs/compiler).

My plan is to bring those packages into gopherjs repository and refactor, clean them up, and eventually `gopherjs serve` functionality will reuse `gopherjs_http.NewFS`. In any case, `gopherjs_http.NewFS` is extremely well supported by me because that's what I use to build all my frontend packages with GopherJS (I don't use the `gopherjs` tool in my build process).

**Comment by beatscode** [comment]
Thank you, this is very helpful.

**Comment by shurcooL** [comment]
Also, those packages are used/explained as part of the [gopherpen](https://github.com/gopherjs/gopherpen) tutorial/project template, FYI.
