### ISSUE TITLE
how to get the return value when I wrapped the function with goroutine

### ISSUE THREAD

**Issue by fearblackcat** [gopherjs/gopherjs#674]
Since the net/http module should be invoked with goroutine block function, I found that I cannot get the response of http even through it was callback normally

So I try to use the following code to resolve it. But it occurs error
```
func GetWrappedRequest(serverurl string) Account {
	accountchan := make(chan Account)

	go func() {
		accountobj := GetDataStr(serverurl)
		accountchan <- accountobj
	}()

	for {
		select{
			case balance := <-accountchan:
			    return balance
		}
	}

}

Error: runtime error: cannot block in JavaScript callback, fix by wrapping code in goroutine
```

**Comment by flimzy** [comment]
Your code is still blocking; now it blocks at `select` instead of at `GetDataStr`.

Without seeing all of your relevant code, it's impossible to know what alternatives might exist, but in general, the solution is not to block.  Use a callback instead (i.e.the JavaScript Way™).  That's rather non-Go idiomatic, but it's one of the consequences of using a JS runtime.

One possible alternative, depending on how your code is organized, might be to invoke the go routine in `GetWrappedRequest`'s caller... then `GetWrappedRequest` will be permitted to block without blocking the JS runtime.

**Comment by fearblackcat** [comment]
@flimzy 
The relevant code of GetWrappedRequest  is in the following

```
func GetDataStr(addr, serverurl string) Account {
	client := &http.Client{
		Transport: http.DefaultTransport,
	}
	req, err := http.NewRequest("POST", "http://xxxxx", bytes.NewBufferString(
		`{"id":1,"account":"1234"]}`,
	))
	req.Header.Set("Content-Type", "application/json")
	response, err := client.Do(req)
	if err != nil {
		println("the error is ", err.Error())
	}

	body, err := ioutil.ReadAll(response.Body)
	defer response.Body.Close()
	if err != nil {
		panic(errors.New("Couldn't parse response body "+err.Error()))
	}
	var dat map[string]interface{}
	json.Unmarshal(body, &dat)
	bn := dat["result"].(map[string]interface{})
	amount := int64(bn["Amount"].(float64))
	amountx := new (big.Int)
	amountx.SetInt64(amount)

	return Account{addr, *amountx}
}

func GetWrappedRequest(addr,  serverurl string) {
	go func() {
		GetDataStr(addr, serverurl)
	}()
}


I mean that how can I get the GetDataStr return value since gopherjs  force me to use goroutine to wrap the GetDataStr
```

**Comment by fearblackcat** [comment]
I confuse that if gopherjs support to get http response

**Comment by fearblackcat** [comment]
Already resolved it. I added a callback function in golang. Just like function pointer. It's a trick
