### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by 4ydx** [gopherjs/gopherjs#699]
GopherJS 1.9-1
Golang 1.9

When building on one of my machines (Ubuntu 16.04.3 LTS), the resulting file is named "..js".  Any thoughts?  Running go build results in a binary that is properly named the parent folder.

I am running build outside the GOPATH.  This appears to be the reason for this so I am now using the "-o" flag in order to specify the resulting filename.  I don't know if this should be considered a bug or not.

**Comment by shurcooL** [comment]
If I understand the issue correctly, the problem is that running `gopherjs build` outside GOPATH produces a suboptimally named "..js" file. Using `go build` produces a better name, using the parent folder name.

I suspect we can fix this, make `gopherjs build` behave as `go build` does.

It would be helpful if you could provide reproducible steps to trigger this.

**Comment by 4ydx** [comment]
go version go1.9 darwin/amd64
GopherJS 1.9-1

In a folder outside GOPATH build the following using gopherjs.

```
package main

import (
	"fmt"

	"github.com/gopherjs/gopherjs/js"
)

func main() {
	fmt.Println("Hello, playground")
	js.Global.Call("alert", "Hello, JavaScript")
	println("Hello, JS console")
}
```

**Comment by 4ydx** [comment]
I have a fix written.  I am a little unclear about the process of getting it approved.
