### ISSUE TITLE
I can't draw image in canvas 

### ISSUE THREAD

**Issue by CHAM0** [gopherjs/gopherjs#716]
Hi, 

(i'm french sorry if i have bad english)

I'm noob with gopherjs and i  have a problem.  i want draw an image on my canvas but  that doesn't works can you help me plz ? 

I build this gofile in jsfile and put him in my html page , the js.Global.Get("document").Call("write", "Test") work but image not.

my code:

```
package main

import (
	"fmt"
	"github.com/gopherjs/gopherjs/js"
)
var player *js.Object
func main() {
	fmt.Println(".")
	js.Global.Get("document").Call("write", "Test")
	player = js.Global.Get("document").Call("createElement", "img")
	player.Set("src", "/Sprites/0.png")
	canvas := js.Global.Get("document").Call("getElementById", "canvas")
	ctx := canvas.Call("getContext", "2d")
	ctx.Call("drawImage", player, 0, 0)
}
```

**Comment by shurcooL** [comment]
Do you see any errors in the browser console?

What is in your HTML file?

The code you posted looks okay, so the issue is likely elsewhere. It's possible that your script runs too soon, before the `<body>` has finished loading, so `canvas := js.Global.Get("document").Call("getElementById", "canvas")` fails to find your `<canvas id="canvas">` element.

Yet another possible problem is that you're setting the `<img>` element's `src` property and immediately rendering the image to your canvas. What will happen is that setting `src` will make the image start loading, but it doesn't wait until it has finished loading before rendering. So you might render an empty image.

To prevent that, you need to wait for image to finish loading. Either do a `time.Sleep(time.Second)` after `player.Set("src", "/Sprites/0.png")`, or better yet:

```Go
player = js.Global.Get("document").Call("createElement", "img")
imageLoaded := make(chan struct{})
player.Call("addEventListener", "load", func() { close(imageLoaded) })
player.Set("src", "/Sprites/0.png")
<-imageLoaded // Wait until image has finished loading.
```

For more information about this, see the "Creating an image from scratch" section of https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Using_images.

The following HTML and script worked successfully for me:

```HTML
<html>
	<head></head>
	<body>
		<canvas id="canvas"></canvas>
		<script src="main.js"></script> <!-- Run script after canvas is available. -->
	</body>
</html>
```

```Go
package main

import (
	"github.com/gopherjs/gopherjs/js"
)

func main() {
	player := js.Global.Get("document").Call("createElement", "img")

	// Load image and wait until it's ready.
	imageLoaded := make(chan struct{})
	player.Call("addEventListener", "load", func() { close(imageLoaded) })
	player.Set("src", "https://mdn.mozillademos.org/files/5397/rhino.jpg")
	<-imageLoaded

	canvas := js.Global.Get("document").Call("getElementById", "canvas")
	ctx := canvas.Call("getContext", "2d")
	ctx.Call("drawImage", player, 0, 0)
}
```

The above renders:

![image](https://user-images.githubusercontent.com/1924134/32501286-9f8040b6-c3a5-11e7-84ec-f3ca6860e59d.png)

**Comment by CHAM0** [comment]
thanks for your help , it's working fine
