### ISSUE TITLE
asm.js ?

### ISSUE THREAD

**Issue by cryptix** [gopherjs/gopherjs#72]
I saw #71 but didn't want to derail the specific issue.

This might be crayz and I guess there are lower hanging fruits to catch first but I wanted to ask for some time if [asm.js](http://asmjs.org/) is/was considered to get better performance. 

For instance, I'm quite positive that code that does a lot of calculation on `int`'s (like game engines or image processing) could get a massive boost out of that. The ahead-of-time  compilation also sounds quite nice with the amounts of code that we are generating now. The TodoMVC example that I cooked up for the wade framework clocks in at 1.4mb of JS now.

I'm also quite sure that this is no easy task, I just wanted to ask.

**Comment by shurcooL** [comment]
I'm sure many people heard of [WebAssembly](https://news.ycombinator.com/item?id=9732827) (also [here](http://techcrunch.com/2015/06/17/google-microsoft-mozilla-and-others-team-up-to-launch-webassembly-a-new-binary-format-for-the-web/) by now.

From what little I know, it seems very interesting and promising, and perhaps it can be on the radar for GopherJS.

**Comment by neelance** [comment]
Yeah, looks promising. But it will take some time until all those high-level features which Go needs are available, e.g. I don't want to manage my own heap.

**Comment by nathany** [comment]
Would it be appropriate for the Go toolchain to target WebAssembly like any other port (ARM64, etc.)? 

Apparently WebAssembly is a binary AST rather than bytecode, so I don't know that impacts the assembler and assembly code that is part of the runtime and standard library.

Still this is all very new, there is no official specification or browser support yet, just a polyfill that converts to asm.js.

**Comment by neelance** [comment]
I'll close this. It is unlikely that GopherJS will ever use asm.js, since using WebAssembly as a backend for the normal Go compiler is the more promising option.
