### ISSUE TITLE
X-Content-Type-Options: nosniff will block gopherjs serve

### ISSUE THREAD

**Issue by linkerlin** [gopherjs/gopherjs#802]
app.js is served as Content-Type: text/plain; charset=utf-8
but with X-Content-Type-Options: nosniff header
the Chrome wil block it with error msg:
Refused to execute script from 'http://localhost:8080/app.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

**Comment by myitcv** [comment]
@linkerlin please can you confirm:

* Chrome version
* Commit of gopherjs you are working against?

Thanks

**Comment by linkerlin** [comment]
Chrome 64bit V 65.0.3325.181
On Linux Mint

**Comment by linkerlin** [comment]
Code: https://github.com/siongui/godom/tree/master/example

**Comment by linkerlin** [comment]
Maybe gopherjs can set `Content-Type: application/x-javascript`  ?

**Comment by linkerlin** [comment]
Thank you for lightning reply!
It works.
But why I got a error msg about : strict MIME type checking?
wondering~

**Comment by myitcv** [comment]
At a pure guess it would be because [`net/http.FileServer`](https://godoc.org/net/http#FileServer) uses [`net/http.ServeContent`](https://godoc.org/net/http#ServeContent) to automatically detect the content type of the 404 response body and concludes, rightly, that it is `text/plain`

This is a derivative error so I'm more surprised that Chrome is even reporting it given the 404 to be honest, so I don't think there's anything to do here in GopherJS-world.

**Comment by myitcv** [comment]
@linkerlin - thanks for raising https://github.com/golang/go/issues/24985; as I mentioned in my comment there, I think this is more of a Chrome issue than anything else. But please do say if you disagree with that conclusion.

**Comment by shurcooL** [comment]
Thanks for helping diagnose the issue @myitcv. It sounds like it's resolved now, the problem was that the HTML included a script with the wrong URL, which gave 404.

I'll close this because it's not an issue in GopherJS.
