### ISSUE TITLE
gopherjs test always fails with deadlock

### ISSUE THREAD

**Issue by jezell** [gopherjs/gopherjs#815]
Create a sample test that does nothing

```
package tmp

import (
	"testing"
)

func Test(t *testing.T) {
}
```
run gopherjs test and though the test is marked as passing, the run fails

```
=== RUN   Test
--- PASS: Test (0.00s)
PASS
fatal error: all goroutines are asleep - deadlock!
FAIL	tmp	0.429s
```

**Comment by shurcooL** [comment]
> Maybe gopherjs test should warn about node-syscall not being installed?

It seems `gopherjs test` requires the syscall module, even though it didn't require it some time ago. I think this is the same issue as #626, so I'll close this as duplicate.

There's also a chance that #710 will fix it, it needs to be finished reviewing.

Otherwise, yes, this should be documented and/or `gopherjs test` can print a warning/error message if the syscall module is unavoidably needed yet missing.
