### ISSUE TITLE
Cannot go get install 

### ISSUE THREAD

**Issue by andyafter** [gopherjs/gopherjs#821]
I am installing with `go get -u ...` from OSX and I get this
```
# cd /Users/andy.pan/gopath/src/golang.org/x/tools; git pull --ff-only
fatal: Not possible to fast-forward, aborting.
package golang.org/x/tools/go/gcexportdata: exit status 128
```

Might be just some simple issue but could anyone help me with this?

**Comment by shurcooL** [comment]
It looks like your `golang.org/x/tools` history has diverged from upstream for some reason. Either you made some local changes to it, or the upstream has force-pushed an incompatible commit (less likely).

The fix is simple. Make sure you don’t have any work you might lose in the `golang.org/x/tools` repository, and simply remove it. Alternatively, you can reset it:

```
cd /Users/andy.pan/gopath/src/golang.org/x/tools
git checkout master
git reset --hard origin/master
```

Then you can try `go get -u github.com/gopherjs/gopherjs` again.

**Comment by andyafter** [comment]
Oh that actually worked!!! Thanks very much!
