### ISSUE TITLE
net/http package (net/http: neither of Fetch nor XMLHttpRequest APIs is available)

### ISSUE THREAD

**Issue by pjebs** [gopherjs/gopherjs#839]
I am making an electron app. `http.Client` works for render process (inside chromium JavaScript) but doesn't work from main process (node js)

It says an error about it not being supported.

How can I make requests from the main process? The compatibility table says I need a polyfill? Why does node js need a polyfill when it works from within chromium. What's the difference?

Is it better to use node library directly or perhaps axios library?

**Comment by shurcooL** [comment]
`http.Client` in GopherJS has 2 implementations: one based on Fetch API, another based on XMLHttpRequest API. It picks whichever is available in that order. Both of those tend to be available in browsers.

Node doesn't seem to provide either one by default, that's why you need a polyfill (either for Fetch or for XHR) for `http.Client` to work under node. The problem seems to be that there wasn't a good one, last time people looked. See previous discussion in #586.

**Comment by pjebs** [comment]
Thanks. Worked it out using assistance from #586 
Step 1:
Add dependency to npm:
`npm install xhr2`

Step 2:
Create a `imports.inc.js` file in the same level as your Go files.

Step 3:
Add `global.XMLHttpRequest = require('xhr2');` to the `imports.inc.js` file.

**Comment by pjebs** [comment]
@shurcooL 
It looks like `xhr2` does not respect context cancellation despite the documentation stating that it supports `abort()`

Do you know how I can make cancelling the request work?

**Comment by pjebs** [comment]
**What I have learnt:**

Dont use net/http to make http requests.
Use `xhr` go package by honnef which uses  `XMLHttpRequest` behind the scenes.

On node js, you need to still add `global.XMLHttpRequest = require('xhr2');`

**Comment by pjebs** [comment]
I created a package that makes it easy: https://github.com/rocketlaunchr/gopherjs-xhr
