### ISSUE TITLE
synchronous calls in goroutine blocks other concurrent goroutines

### ISSUE THREAD

**Issue by pjebs** [gopherjs/gopherjs#849]
I have 1 goroutine which contains a call to a synchronous function.

I have many other independent concurrent goroutines which ordinarily would run concurrently. But they don't run until the synchronous function returns.

**Comment by pjebs** [comment]
I also have a:
```
		js.Global.Call("setInterval", func() {
			println("test 1")
		}, 1000)
```

This is outside of any goroutines I have created. (assume it is called from main).
This continually works and is not blocked. This implies the main runloop itself is not blocked.

**Comment by theclapp** [comment]
> I have 1 goroutine which contains a call to a synchronous function.

What does the synchronous function look like / do?  Is it Go or regular Javascript?

```go
		js.Global.Call("setInterval", func() {
			println("test 1")
		}, 1000)
```

> This continually works and is not blocked. This implies the main runloop itself is not blocked.

I'm not sure I agree.  This would

**Comment by pjebs** [comment]
The synchronous function is a non-Go function (electron function).

**Comment by pjebs** [comment]
Do you have any ideas why a synchronous function inside a goroutine would prevent other independent goroutines from running? That's definitely not the case in standard go.

**Comment by pjebs** [comment]
I can also see that the synchronous function is effecting the network request from returning:

I have a different goroutine with a polyfilled `net.http.Client.Do( req )`. The request doesn't return until the synchronous function returns: https://github.com/gopherjs/gopherjs/issues/839

@dmitshur

**Comment by theclapp** [comment]
> Do you have any ideas why a synchronous function inside a goroutine would prevent other independent goroutines from running? That's definitely not the case in standard go.

The synchronous function is not Go, so it blocks the Go scheduler.

It's as if in regular Go (before, I wanna say, 1.5?) you set MAXPROCS to 1 and then started a goroutine that just sat in a loop doing no function calls.  The scheduler doesn't run.

GopherJS is not Go (though obviously it does its best).  It compiles to Javascript.  Javascript is single threaded.  If some Javascript function blocks the rest of the Javascript engine, then there's nothing magical about GopherJS that can get around that, it'll block too.

**Comment by pjebs** [comment]
The non-synchronous function doesn't seem to block entire javascript engine:
https://github.com/electron/electron/issues/13820#issuecomment-412129244
In the non-go version of my code, the `console.log('test');` still runs continually.


A redacted Go-version (which is what I actually use):
```
	popupMenu := func() {
		// Show standard menu
		go func() {
			contextMenu := mm.buildMainMenu()
			mm.tray.PopUpContextMenu(contextMenu, &electron.TrayPopUpContextMenuPosition{}) // This blocks all goroutines until menu is closed
		}()
	}

	mm.tray.On(electron.EvtTrayClick, func(args ...*js.Object) { go popupMenu() })
```

**Comment by theclapp** [comment]
[setTimeout not working reliably](https://github.com/electron/electron/issues/7079)  may be relevant: GopherJS uses [`setTimeout(<scheduler>, 0)`](https://github.com/gopherjs/gopherjs/blob/master/compiler/prelude/goroutines.go#L167) to schedule goroutines.

Instead of testing with `setInterval`, can you try a `setTimeout` background loop, and see if that pauses or runs erratically?

When you say the main thread is blocked, how long do you wait?  https://github.com/electron/electron/issues/7079#issuecomment-244561458 mentions 10+ second delays.

**Comment by pjebs** [comment]
I added:
```
	js.Global.Call("setInterval", func() {
		println("test1") // This works
	}, 1000)

	go func() {
		for {
			js.Global.Call("setTimeout", func() {
				println("test2") // This is blocked until menu is closed
			}, 1000)
			time.Sleep(time.Second)
		}
	}()
```

I tried `setTimeout` but until the menu is closed, the timer stops running. It restarts again after menu is closed.

**Comment by theclapp** [comment]
I think to test if `setTimeout` is broken, the `setTimeout`'d function would have to reset itself.  Something along the lines of (untested)

```go
var f func()
f = func() {
    println("test2")
    js.Global.Call("setTimeout", f, 1000)
}
f()
```

As it is, you've got a stalled goroutine, which we already know doesn't work.

I was also thinking that, since `setInterval` (apparently?) does still work, you might also try

```go
js.Global.Call("setInterval", func() {
	runtime.Gosched()
}, 1000)
```

on the theory that this might let the GopherJS scheduler run, but then I looked at [the source to Gosched](https://github.com/gopherjs/gopherjs/blob/4e9f423448a0b0462d41b077c43bb9f2a5d103c6/compiler/natives/src/runtime/runtime.go#L97), and it just calls `setTimeout` (indirectly).  Alas.  That said, you might give it a shot, just to make sure it won't help.

**Comment by pjebs** [comment]
`Gosched` just caused a panic stating `cannot block in JavaScript callback, fix by wrapping code in goroutine`

**Comment by pjebs** [comment]
I still think this is a gopherjs bug that a synchronous code is able to block all independent goroutines. @dmitshur

**Comment by pjebs** [comment]
I made a discovery. I replaced the synchronous code with a `blocking Go function` and it works.

I replaced original code:

```
js.Global.Call("setInterval", func() {
	println("test") // This is not blocked by synchronous function
}, 1000) 


popupMenu := func() {
	// Show standard menu
	go func() {
		contextMenu := mm.buildMainMenu()
		// This blocks all goroutines until menu is closed
		mm.tray.PopUpContextMenu(contextMenu, &electron.TrayPopUpContextMenuPosition{})
	}()
}

mm.tray.On(electron.EvtTrayClick, func(args ...*js.Object) { go popupMenu() })
```

Now:

```

js.Global.Call("setInterval", func() {
	println("test") // This is not blocked by synchronous function
}, 1000) 

block := func() {
	time.Sleep(30 * time.Second)
}

popupMenu := func() {
	// Show standard menu
	go func() {
		contextMenu := mm.buildMainMenu()
		// This blocks all goroutines until menu is closed
		block()
	}()
}

mm.tray.On(electron.EvtTrayClick, func(args ...*js.Object) { go popupMenu() })

**Comment by pjebs** [comment]
The `block` function "simulates" a synchronous function and it works well.

@dmitshur @theclapp It seems like gopher js Scheduler doesn't know how to deal with synchronous non-Go functions. Shouldn't this be considered a bug? Is it a simple fix? Where in the code should I start looking?

**Comment by pjebs** [comment]
The non-Go function is an electron function which I suspect is a node.js function which wraps a Objective-C++ functions.

**Comment by theclapp** [comment]
Thank you for verifying that `Gosched` wouldn't work.  It broke for a different reason than I expected, but whatever.  :)

---

The `block` function you tested in place of `mm.tray.PopUpContextMenu` is not actually a blocking call.  It sleeps.  In GopherJS, `time.Sleep` is [implemented](https://github.com/gopherjs/gopherjs/blob/master/compiler/natives/src/time/time.go#L50) in terms of `setTimeout` (which we're theorizing is broken):

```go
func Sleep(d Duration) {
	c := make(chan struct{})
	js.Global.Call("$setTimeout", js.InternalObject(func() { close(c) }), int(d/Millisecond))
	<-c
}
```

I've played around for a while, simulating a blocking function with

```go
block := func() {
	for n := 0; n < busyloop; n++ {
		_ = n
	}
}
```

(where busyloop is a variable I can increase outside of the blocked function), and different ways of calling `time.Sleep` or `runtime.Gosched` or `js.Global.Call("$runScheduled")`, and can't ever get a `setInterval`'d function to "break in" in the middle of some other goroutine.

It does appear that you can call `$runScheduled` yourself, and I never got a panic or anything (though that might be a false negative), but the runtime doesn't really expect that, and it didn't help.  Or at least I couldn't get it to make a difference.  It might in your case, since you have a different type of blocking call, with other real goroutines going on that are doing real things (as opposed to mine that were mostly twiddling their metaphorical thumbs).

So here's what I tried if you want to try it:

```go
js.Global.Call("setInterval",
	js.InternalObject(js.Global.Get("$runScheduled")),
	10)
```

which compiles to

```js
$global.setInterval($runScheduled, 10);
```

---

@dmitshur I'm about out of ideas.  Please take a look at this when you get a chance.  I'd recommend you take special notice of https://github.com/electron/electron/issues/7079, which discusses `setTimeout` being fairly broken in Electron, @pjebs's current platform.
