### ISSUE TITLE
Extract js package to another repo

### ISSUE THREAD

**Issue by cristaloleg** [gopherjs/gopherjs#919]
Currently, while GopherJS API is presented in the package js (https://github.com/gopherjs/gopherjs/tree/master/js). And to use it every user needs to check out a quite heavy `github.com/gopherjs/gopherjs` repo.

I'm proposing to extract `js` package to a new repo (probably `github.com/gopherjs/js`) and alias its types in `github.com/gopherjs/gopherjs/js`.

The back compatibility will be safe, users will use(depend) on a much smaller package, we can introduce Go modules to the new package with out any problems(hopefully).

I hope I'm not missing something and it's possible to make. Thank you.

UPD: aliases were added in 1.9, I'm not sure what is the minimal supported version for gopherjs.

**Comment by dmitshur** [comment]
This is a reasonable feature request to consider. It should be possible to accomplish this, but it would take a fair bit of implementation work (which is hard due to #894). It also has the downside of potentially creating churn (people updating `github.com/gopherjs/gopherjs/js` import paths in various places). It's a big enough change we'd need to decide if we're willing to support it.

As an alternative, have you considered using the `syscall/js` API? GopherJS supports it as of version 1.12-2. See issue #899. It has the benefit of being in the standard library and no third-party package download needed at all. /cc @hajimehoshi

**Comment by hajimehoshi** [comment]
`syscall/js` sounds enough to me for your request.

**Comment by cristaloleg** [comment]
`syscall/js` looks like a solution, thank you.

(I will leave this issue open for some time, ok?)

**Comment by cristaloleg** [comment]
Probably `syscall/js` is a proper solution for that. Closing.
