### ISSUE TITLE
JS object should be json unmarshalled into the target Go type

### ISSUE THREAD

**Issue by benma** [gopherjs/gopherjs#976]
Currently, when passing a object from JS to a gopherjs compiled function, the param type in the Go code has to be `map[string]interface{}`, so .e.g `{ "foo": "bar" }` results in `map[string]interface{}{"foo": "bar"}` in Go.

Most of the times though, the object is more structured, and I'd like to use a struct type instead:

```Go
type struct Param {
    Foo string `json:"foo"`
}
```

This is currently not accepted, and I manually transform the map into the struct. 

When going froim JS to Go, would it make sense to just use `json.Unmarshal()`? It will work the same way for `map[string]interface{}`, but would allow much easier use with less boilerplate in general.

**Comment by flimzy** [comment]
Are you aware of the available `js` tag? https://github.com/gopherjs/gopherjs/wiki/JavaScript-Tips-and-Gotchas

**Comment by benma** [comment]
In fact I was not aware, thanks ;) Would be good to mention this in https://pkg.go.dev/github.com/gopherjs/gopherjs/js

I have a struct where some fields are optional. Neither `omitempty` nor making the type a pointer seems to work. Any ideas?

E.g.

```Go
type S struct {
    A int `js:"a,omitempty"`
    B int `js:"b,omitempty"`
}
```

So that if `{"a": 1}` is provided, B just defaults to 0 (or nil if both were `*int`).

**Comment by nevkontakte** [comment]
@benma you could use a library like https://pkg.go.dev/github.com/mitchellh/mapstructure to map from `map[string]interface{}` onto a Go struct.

I am not sure adding optional field support is a good idea for a few reasons:

 1. It can easily mask programming errors when an object object of a wrong type is passed in from JS code (and therefore can't be reliably type checked by GopherJS).
 2. It would require the compiler to generate runtime checks for every access of the field, which brings performance penalty.
 3. Subjectively, this is a bit more magical than Go is meant to be 🙂
 4. Arguably it is better to provide getters for optional fields, since that gives you the control over what the default behavior should be.

**Comment by nevkontakte** [comment]
Considering lack of activity, I'm closing this issue. Please let us know if you still think this is an issue and we can reopen it.
