### ISSUE TITLE
Atomics.wait

### ISSUE THREAD

**Issue by hsiaosiyuan0** [gopherjs/gopherjs#986]
[Atomics.wait](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics/wait) is included in nodejs from 8.10.0, might it be used to implement go's channel ?:)

**Comment by flimzy** [comment]
Thanks for submitting this. However, please note that the GopherJS project is now frozen. See [this thread](https://github.com/gopherjs/gopherjs/issues/894#issuecomment-766547185) for details. The final freezing of this repo is scheduled to happen within a week.

**Comment by hsiaosiyuan0** [comment]
@flimzy thank you but such a heartbreaking news it is 😢

**Comment by mcaubrey** [comment]
Have any recommendations for another Go to JS library?

**Comment by flimzy** [comment]
@mcaubrey We've had a breath of fresh air on this project, so stay tuned for some announcements in the coming week or two.

**Comment by nevkontakte** [comment]
This is an interesting proposal, but not a trivial one to implement. As far as I can tell, this function was introduced in [ECMAScript 8.0](https://262.ecma-international.org/8.0/) specification, and at the moment GopherJS targets output compatibility with ES5, so until we change that, we can't really use `Atomics.wait()` without a shim. It is possible that we'll begin targeting more modern versions of ES at some future point, but this is up in the air at the moment.

The MDB article also has this warning:

> This operation only works with a shared Int32Array and may not be allowed on the main thread.

Considering that GopherJS does execute in the main thread in the browser, this may be a no-go entirely :( Unless there's a strong objection, I'm going to close this issue for now, but I'll tag it with the `ECMAScript 6+` label so that we can revisit it if/when we are ready to explore targeting newer versions of JS.
